import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import Footer from "./_components/footer";
import MediaHeader from "./_components/media-header";
import Navbar from "./_components/navbar";
import "./globals.css";

const Firacode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Firacode.variable}  `}>
      <body className={` font-fira-code `}>
        <MediaHeader />
        <div className="container mx-auto w-full">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
